# docker-compose.yml

version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: stt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: stt_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
